///////////////////////////////////////////////////////////
//  AbstractBox.cs
//  Implementation of the Class AbstractBox
//  Generated by Enterprise Architect
//  Created on:      16-11月-2016 19:47:10
//  Original author: ant_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using  System.Linq;



namespace AntDesigner.GameCityBase.boxs {
    public  class Box {

        public string Name{get;set;}
		/// <summary>
		/// 赔率
		/// </summary>
		public byte Odds{ get;  set;} 
		/// <summary>
		/// 中奖权重
		/// </summary>
		public byte WeightCoefficient{ get;  set;}
        public int Prize { get; set; }
        public Box(string name_, byte odds_, byte weightCoefficeint_){
           Name = name_;
            Odds = odds_;
            WeightCoefficient = weightCoefficeint_;

		}


	}//end AbstractBox

}//end namespace boxs