///////////////////////////////////////////////////////////
//  GemePanel.cs
//  Implementation of the Class GemePanel
//  Generated by Enterprise Architect
//  Created on:      16-11ÔÂ-2016 19:47:11
//  Original author: ant_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using  System.Linq;



using AntDesigner.GameCityBase.boxs;
namespace AntDesigner.GameCityBase
{
	public class GemePanel {

		public GemePanel(){

			
		}
		public ICollection<Box> BoxCotainer{
			get;
			set;
		}

		public AntDesigner.GameCityBase.boxs.Box StartGeme(){

			return null;
		}

	}//end GemePanel

}//end namespace AntDesigner.AppleGame