///////////////////////////////////////////////////////////
//  AccountDetail.cs
//  Implementation of the Class AccountDetail
//  Generated by Enterprise Architect
//  Created on:      16-11月-2016 19:47:10
//  Original author: ant_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



using AntDesigner.AppleGame;
using AntDesigner.GameCityBase.interFace;
using System.ComponentModel.DataAnnotations.Schema;

namespace AntDesigner.GameCityBase
{/// <summary>
/// 账户变动明细
/// </summary>
	public class AccountDetail {
		public int Id{
			get;
			set;
		}
        /// <summary>
        /// 变动金额
        /// </summary>
		public decimal Amount{ get;  set;} 
        /// <summary>
        /// 变动原因
        /// </summary>
		public string Explain{ get;  set;} 
        /// <summary>
        /// 账户
        /// </summary>
		public Account Account { get; set; }
      
		public AccountDetail(){

		}
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreateTime
        {
            get; set;
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime ModifyTime
        { get; set; }

    }//end AccountDetail

}//end namespace AntDesigner.AppleGame