///////////////////////////////////////////////////////////
//  ManagePlayer.cs
//  Implementation of the Class ManagePlayer
//  Generated by Enterprise Architect
//  Created on:      16-11ÔÂ-2016 19:47:11
//  Original author: ant_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using AntDesigner.NetCore.GameCity;


using AntDesigner.AppleGame;
using AntDesigner.weiXinPay;
using AntDesigner.GameCityBase.boxs;

namespace AntDesigner.GameCityBase
{
    public class ManagePlayer : Player
    {
        public static readonly ManagePlayer Instance = new ManagePlayer();
        public static Func<ManagePlayer> DgetManagePlayer { get; set; }
        private static ManagePlayer OnlyInstance = null;
        private static object LockHelper = new object();
        public static ManagePlayer GetOnlyInstance()
        {
            if (OnlyInstance == null)
            {
                lock (LockHelper)
                {
                    if (OnlyInstance == null)
                    {

                        OnlyInstance = DgetManagePlayer();
                    }
                }
            }
            return OnlyInstance;
        }
        public ManagePlayer()
        {
        }
        public void SetGameDegree(string gameDegree)
        {
            BoxsManager.Degree = gameDegree;
        }

    }//end ManagePlayer

}//end namespace AntDesigner.AppleGame