///////////////////////////////////////////////////////////
//  Message.cs
//  Implementation of the Class Message
//  Generated by Enterprise Architect
//  Created on:      16-11月-2016 19:47:11
//  Original author: ant_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using AntDesigner.GameCityBase;
using AntDesigner.GameCityBase.interFace;
using System.ComponentModel.DataAnnotations.Schema;

namespace AntDesigner.GameCityBase
{
	public class Message  {
        public int Id
        {
            get;
            set;
        }
        /// <summary>
        /// 消息内容
        /// </summary>
        public string Content{ get;  set;} 
		/// <summary>
		/// 接收者
		/// </summary>
		public Player Receiver{ get;  set;} 
		/// <summary>
		/// 回复内容
		/// </summary>
		public string ReplyContent{ get;  set;} 
		/// <summary>
		/// 发送者
		/// </summary>
		public Player Sender{ get;  set;} 
		public Message(){

		}
        public Message(Player sender_,string content_,Player receiver_)
        {
            Sender = sender_;
            Content = content_;
            Receiver = receiver_;
        }
        /// 
        /// <param name="player"></param>
        /// <param name="content"></param>
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreateTime
        {
            get; set;
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime ModifyTime
        { get; set; }
    }//end Message
}//end namespace AntDesigner.AppleGame