///////////////////////////////////////////////////////////
// Player.cs
// Implementation of the Class Player
// Generated by Enterprise Architect
// Created on: 16-11月-2016 19:47:12
// Original author: ant_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using AntDesigner.NetCore.GameCity;
using AntDesigner.GameCityBase.interFace;
namespace AntDesigner.GameCityBase
{
    public class Player :  IPlayerJoinRoom, ICityManager
    {

      //  public static Func<Player, IList<Player>> DgetFriendsOfPlayer { get; set; }
     //   public static Func<Player, IList<Message>> DgetMessagesOfPlayer { get; set; }
      //  public static Func<Message, Message> DsaveNewMessage { get; set; }
        public static Func<Player,decimal,string,decimal> DDecutMoney { get;set;}
        //internal IList<Message> SeeMessags()
        //{
        //    return DgetMessagesOfPlayer(this);
        //}
        public Player()
        {

        }
        public Player(string name) : this()
        {
            WeixinName = name;

        }
        public Account Account
        {
            get;
            set;
        }
        //public IList<Player> SeeFriends()
        //{
        //    return DgetFriendsOfPlayer(this);
        //}
        /// <summary>
        /// 提现
        /// </summary>
        /// <param name="amount"></param>
        public void Drow(decimal amount)
        {

        }
        public IList<AccountDetail> GetAccountDetails()
        {

            return this.Account.AccountDetails;
        }
        /// <summary>
        /// 充值
        /// </summary>
        /// <param name="amount"></param>
        public void Recharge(decimal amount)
        {

        }
        ///
        /// <param name="message"></param>
        public Message ReplyMessage(Message message, string content)
        {

            message.ReplyContent = content;
            return message;
        }
        /// <param name="reveiver"></param>
        /// <param name="content"></param>
        //public Message SendMessageTo(Player receiver, string content)
        //{

        //    Message message = new Message(this, content, receiver);
        //    DsaveNewMessage(message);
        //    return message;
        //}
        public bool DecutMoney(decimal amount, string cause)
        {
            if (amount==0)
            {
                return true;
            }
            try
            {
                if (DDecutMoney != null)
                {
                    this.Account.Balance = DDecutMoney.Invoke(this, amount, cause);
                }
                return true;
            }
            catch (Exception)
            {

                return false;
            }

            //try
            //{
            //    this.Account.Addmount(-ticketPrice_, cause);
            //    return true;
            //}
            //catch (Exception)
            //{

            //    return false;
            //}
        }
        public bool AccountNotEnough(decimal ammount_)
        {
            if (Account.Balance<ammount_)
            {
                return true;
            }
            return false;
        }
        [Required]
        public string WeixinName
        {
            get;
            set;
        }
        public int Id
        {
            get;
            set;
        }
        public string IntroducerWeixinName { get; set; }
        public bool OnlineState { get; set; }
        decimal IPlayerJoinRoom.Account { get { return this.Account.Balance; }set { Account.Balance = value; } }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreateTime
        {
            get; set;
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime ModifyTime
        { get; set; }
        [NotMapped]
        public object WebSocketLink { get ; set ; }
    }//end Player

}//end namespace AntDesigner.AppleGame